server:
  port: 8080
  max-http-request-header-size: 8KB
  tomcat:
    max-http-response-header-size: 8KB

spring:
  application:
    name: PureSound API

  profiles:
    active: test

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 0
    fallback-to-system-locale: false
    always-use-message-format: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Facebook

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: sub

          facebook:
            authorization-uri: https://www.facebook.com/v23.0/dialog/oauth
            token-uri: https://graph.facebook.com/v23.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v23.0/me?fields=email,first_name,last_name,picture
            user-name-attribute: id

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          startssl:
            enable: true
          auth: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    csrf:
      enabled: false

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

jwt:
  secret: ${JWT_SECRET}
  exp-at-min: ${EXP_AT_MIN}
  exp-rt-min: ${EXP_RT_MIN}

listener:
  callback-url: ${LISTENER_CALLBACK_URL}

artist:
  callback-url: ${ARTIST_CALLBACK_URL}

otp:
  signup:
    exp-min: ${OTP_SIGNUP_EXP_MIN}

nominatim:
  url: https://nominatim.openstreetmap.org/reverse

weatherApi:
  url: https://api.weatherapi.com/v1/current.json
  key: ${WEATHER_API_KEY}

minio:
  endpoint: ${MINIO_ENDPOINT_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  buckets:
    tracks: puresound-tracks

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
