server:
  port: 8080
  max-http-request-header-size: 8KB
  tomcat:
    max-http-response-header-size: 8KB

spring:
  application:
    name: puresound-backend

  profiles:
    active: dev

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 0
    fallback-to-system-locale: false
    always-use-message-format: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    csrf:
      enabled: false

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
